import Head from "next/head";
import { Screen } from "@/components";

const Index = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Leonardo Moraes - Portifolio</title>
      </Head>
      <Screen>
        <h1>Minha página!</h1>
      </Screen>
    </>
  );
};

export default Index;
